
---
- name: Create azure network
  hosts: azure
  connection: local
  tasks:
  
  - name: Add virtual mashine
    azure_rm_virtualmachine:
      resource_group: "my-network"
      open_ports: 22, 9000, 21000, 22000, 50400
      name: testVM
      vm_size: Standard_B1s
      admin_username: lesha
      ssh_password_enabled: false
      ssh_public_keys: 
        - path: /home/lesha/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnY40Qytw0d3dOk438k3yNiKaIRir42MRERY7ab+/XwIVqd39FqzZu6kMi4QED+D57X7wYE+a7xm81rLNFKjGEibXLZq+qjHuMRl/ySQOF3a7h9e7V4HuYIxooV/p2CDE8lART+6LkVwG6cEvwc4+bNx/61KZwTqHQh15SozWFNV9XgTMmx8KYLH8YaKUyMzts5tRWVccUJ4+3CKyk7xtA57o0Js0g1fVU8jgMubEiQmFq6vEOyK+etp9JmDosvahz3Xewwn5FR5fIGrdVtjc9fHFrw1blzwaCq1zxsqRILkQCoYGtbLo2/gkDa07seGsM9mUJJStbcG3u3bZxfH55" 
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
    
  
  - name: Get Public IP
    azure_rm_publicipaddress_facts:
      resource_group: '{{ "my-network" }}'
    register: azure_ip

  - debug: 
    msg: "IP is {{ azure_ip.azure_publicipaddresses }}"

  #- name: Add new instance to host group
  #  add_host:
  #    hostname: "{{ item.properties.ipAddress }}"
  #    groupname: launched
  #  with_items: "{{ azure_ip.ansible_facts.azure_publicipaddresses }}"