---
# tasks file for add_users
  - name: add user lesha
    user:
      name: lesha
      # XxPw4_uF7
      password: '$6$sqv4RHac8iGUNL5b$hhh5sVM7vvHMoomdrK8tWmC1A4yxIg5S4GHxT7Nt3QWdu4gmwSed.W0jj2VLwRjSMdGxlAHUk74nTOGeYZbgz1'
      shell: /bin/bash

  - name: Set authorized key took from file
    authorized_key:
      user: lesha
      state: present
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpaHcmEEREzhGOY9jOZMhA4ERn7x/ksy95iPGd1PJ0qY+wIPRXwpakn22zvsVwgOXjwHfME1KjsaTXQ0s72tDm1ggbKutZhGcYcB6Ltu2JKImXNiShRI7Ghxau3yArv1C5KbZBQ/i+vKCPKvavyNkpkSQ/rPTgH6HLiwpQnUz/9Fvc+HBTxXMilSupkDYzyMehVMwKzVp3FzoN1LrmQb1wGEWkGNBFd5DZrHXCe8y+y4x7CD6tEertGRG0m270SgOMRcFwrhxJ4rneeqUAvxhFHSBdC2a6wLDTmX0Sa/krbzpqVT0xuaUdcu15BXJM443eBVivySO1Hjb/lVoxfUhh lesha@leshas-MacBook-Air.local'

  - name: color bash
    copy:
      src: bash_profile
      dest: /home/lesha/.bash_profile
      owner: lesha
      group: lesha
      mode: 0644

  - name: add user ops
    user:
      name: ops
      # XxPw4_uF7
      password: '$6$sqv4RHac8iGUNL5b$hhh5sVM7vvHMoomdrK8tWmC1A4yxIg5S4GHxT7Nt3QWdu4gmwSed.W0jj2VLwRjSMdGxlAHUk74nTOGeYZbgz1'
      shell: /bin/bash

  - name: Set authorized key took from file
    authorized_key:
      user: ops
      state: present
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpaHcmEEREzhGOY9jOZMhA4ERn7x/ksy95iPGd1PJ0qY+wIPRXwpakn22zvsVwgOXjwHfME1KjsaTXQ0s72tDm1ggbKutZhGcYcB6Ltu2JKImXNiShRI7Ghxau3yArv1C5KbZBQ/i+vKCPKvavyNkpkSQ/rPTgH6HLiwpQnUz/9Fvc+HBTxXMilSupkDYzyMehVMwKzVp3FzoN1LrmQb1wGEWkGNBFd5DZrHXCe8y+y4x7CD6tEertGRG0m270SgOMRcFwrhxJ4rneeqUAvxhFHSBdC2a6wLDTmX0Sa/krbzpqVT0xuaUdcu15BXJM443eBVivySO1Hjb/lVoxfUhh lesha@leshas-MacBook-Air.local'
  
  - name: is sudo present
    stat: 
      path: /etc/sudoers
    register: sudoers
    become: false

  - name: include sudoers.d
    lineinfile:
      dest: /etc/sudoers
      regexp: '^#includedir '
      line: '#includedir /etc/sudoers.d'
      validate: visudo -cf %s

  - name: setup sudo
    template:
      src: 95-ansible-users.j2
      dest: /etc/sudoers.d/95-ansible-users
      mode: 0440
      validate: visudo -cf %s
