# tasks file for tomcat setup

- name: create user for tomcat
  user:
    name: tomcat
    shell: /bin/nologin 
    home: /opt/tomcat

- name: Download Tomcat Binary
  get_url:
    url: http://www-us.apache.org/dist/tomcat/tomcat-9/v9.0.10/bin/apache-tomcat-9.0.10.tar.gz
    dest: /opt/tomcat/apache-tomcat-9.0.10.tar.gz
    mode: 0755

- name: extract tomcat
  # unarchive:
  #   src: /opt/tomcat/apache-tomcat-9.0.10.tar.gz
  #   dest: /opt/tomcat
  #   remote_src: yes
  shell: tar xvf /opt/tomcat/apache-tomcat-9.0.10.tar.gz -C /opt/tomcat --strip-components=1

- name: copy systemd unit file
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: u=rw,g=r

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: update /opt/tomcat/conf/tomcat-users.xml
  lineinfile:
    path: /opt/tomcat/conf/tomcat-users.xml
    #regexp: '^</tomcat-users>'
    insertbefore: '^</tomcat-users>'
    line: '<user username="admin" password="FIVZKH9mp4XjvE0" roles="manager-gui,admin-gui"/>'

- name: change the IP address restrictions 
  copy:
    src: contex.xml
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml
    owner: tomcat
    group: tomcat
    mode: u=rw,g=r

- name: change the IP address restrictions 
  copy:
    src: contex.xml
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
    owner: tomcat
    group: tomcat
    mode: u=rw,g=r

- name: change permission for /opt/tomcat
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: 0755
    recurse: yes  

- name: enable and start tomcat
  systemd:
    name: tomcat
    enabled: yes
    state: restarted
