---
# tasks file for nginx setup on debian 9
- name: Install nessesary package
  apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
    - apt-transport-https
    - build-essential
    - gcc
    - g++
    - make

- name: nginx download singing key
#   get_url:
#     url: http://nginx.org/keys/nginx_signing.key
#     dest: /home/ops/nginx_signing.key
#     mode: 0755
  shell: wget http://nginx.org/packages/keys/nginx_signing.key && cat nginx_signing.key | apt-key add -

- name: add nginx repo
  apt_repository:
    repo: deb http://nginx.org/packages/mainline/debian/ stretch nginx
    state: present  


- name: install nginx
  apt: 
      name: nginx
      state: present
      update_cache: yes

- name: create directory /etc/nginx/ssl/private
  file:
    path: /etc/nginx/ssl/private
    state: directory
    mode: 0755

- name: create directory /etc/nginx/ssl/certs
  file:
    path: /etc/nginx/ssl/certs
    state: directory
    mode: 0755
  

- name: add nginx configs
  copy:
    src: nginx-proxy.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: add nginx configs
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: Ensure NGINX is running and and enabled to start automatically on reboots
  systemd:
    name: nginx
    enabled: yes
    state: started
    





