---
# tasks file for nginx and nodejs setup on debian 9
- name: Install nessesary package
  apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
    - apt-transport-https
    - build-essential
    - gcc
    - g++
    - make

- name: install nodejs repo for nodejs 10
  shell: curl -sL https://deb.nodesource.com/setup_10.x | bash -

- name: install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes

