---
# tasks file for quorum setup

- name: Download GO
  get_url:
    url: https://storage.googleapis.com/golang/{{ GOREL }}
    dest: /home/lesha/{{ GOREL }}
    owner: lesha
    group: lesha
    mode: 0755

## Uncoment after playbook complete    
- name: Unpack go
  shell: tar xvf {{GOREL}} && mv go /usr/local/go

- name: set Go to PATH
  shell: export PATH=$PATH:/usr/local/go/bin

- name: set Go PATH to lesha .profile
  lineinfile:
    path: /home/lesha/.profile
    regexp: '^#export GOPATH '
    line: export PATH=$PATH:/usr/local/go/bin

- name: set Go PATH to ops .profile
  lineinfile:
    path: /home/ops/.bashrc
    regexp: '^#export GOPATH '
    line: export PATH=$PATH:/usr/local/go/bin

- name: set Go PATH to root .profile
  lineinfile:
    path: /root/.profile
    regexp: '^#export GOPATH '
    line: export PATH=$PATH:/usr/local/go/bin

- name: source .profile
  shell: source /home/lesha/.profile | bash

- name: Clean folder after go downloads
  file:
    path: /home/lesha/{{GOREL}} 
    state: absent

