---
# tasks file for add_users
  - name: add user lesha
    user:
      name: lesha
      # XxPw4_uF7
      password: '$6$sqv4RHac8iGUNL5b$hhh5sVM7vvHMoomdrK8tWmC1A4yxIg5S4GHxT7Nt3QWdu4gmwSed.W0jj2VLwRjSMdGxlAHUk74nTOGeYZbgz1'
      shell: /bin/bash

  - name: Set authorized key took from file
    authorized_key:
      user: lesha
      state: present
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnY40Qytw0d3dOk438k3yNiKaIRir42MRERY7ab+/XwIVqd39FqzZu6kMi4QED+D57X7wYE+a7xm81rLNFKjGEibXLZq+qjHuMRl/ySQOF3a7h9e7V4HuYIxooV/p2CDE8lART+6LkVwG6cEvwc4+bNx/61KZwTqHQh15SozWFNV9XgTMmx8KYLH8YaKUyMzts5tRWVccUJ4+3CKyk7xtA57o0Js0g1fVU8jgMubEiQmFq6vEOyK+etp9JmDosvahz3Xewwn5FR5fIGrdVtjc9fHFrw1blzwaCq1zxsqRILkQCoYGtbLo2/gkDa07seGsM9mUJJStbcG3u3bZxfH55 lesha@lesha-acer'

  - name: add user ops
    user:
      name: ops
      # XxPw4_uF7
      password: '$6$sqv4RHac8iGUNL5b$hhh5sVM7vvHMoomdrK8tWmC1A4yxIg5S4GHxT7Nt3QWdu4gmwSed.W0jj2VLwRjSMdGxlAHUk74nTOGeYZbgz1'
      shell: /bin/bash

  - name: Set authorized key took from file
    authorized_key:
      user: ops
      state: present
      key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpaHcmEEREzhGOY9jOZMhA4ERn7x/ksy95iPGd1PJ0qY+wIPRXwpakn22zvsVwgOXjwHfME1KjsaTXQ0s72tDm1ggbKutZhGcYcB6Ltu2JKImXNiShRI7Ghxau3yArv1C5KbZBQ/i+vKCPKvavyNkpkSQ/rPTgH6HLiwpQnUz/9Fvc+HBTxXMilSupkDYzyMehVMwKzVp3FzoN1LrmQb1wGEWkGNBFd5DZrHXCe8y+y4x7CD6tEertGRG0m270SgOMRcFwrhxJ4rneeqUAvxhFHSBdC2a6wLDTmX0Sa/krbzpqVT0xuaUdcu15BXJM443eBVivySO1Hjb/lVoxfUhh lesha@leshas-MacBook-Air.local'
  
  - name: is sudo present
    stat: 
      path: /etc/sudoers
    register: sudoers
    become: false

  - name: include sudoers.d
    lineinfile:
      dest: /etc/sudoers
      regexp: '^#includedir '
      line: '#includedir /etc/sudoers.d'
      validate: visudo -cf %s

  - name: setup sudo
    template:
      src: 95-ansible-users.j2
      dest: /etc/sudoers.d/95-ansible-users
      mode: 0440
      validate: visudo -cf %s
