# tasks file for Oracle Java 8 setup
- name: Install nessesary packeges

  apt: 
      name: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
    - software-properties-common
    - dirmngr
  
- name: add gpg key
  apt_key:
    id: EEA14886
    keyserver: keyserver.ubuntu.com

- name: Add Oracle Java Repository
  apt_repository: 
    repo: "{{item}}"
    state: present
  with_items:
    - deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main
    - deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main

- name: Accept Java 8 License
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: Install Oracle Java 8
  apt: 
      name: "{{item}}"
      state: latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default