---
# tasks file for elixir backend CI

- name: stop rp_server daemon
  shell: HOSTNAME=127.0.0.1 REPLACE_OS_VARS=true sh /home/ops/rp-server/_build/prod/rel/rp_server/bin stop

- name: delete old _build folder
  file:
    path: /home/ops/rp-server/_build
    state: "{{ item }}"
  with_items:
    - directory
    - absent

- name: delete old deps folder
  file:
    path: /home/ops/rp-server/deps
    state: "{{ item }}"
  with_items:
    - directory
    - absent

- name: delete old mix.lockg
  file:
    path: /home/ops/rp-server/mix.lock
    state: absent

- name: clone rp_server repo
  git:
      repo: 'git@github.com:Kimlic/rp_server.git'
      dest: /home/ops/rp-server
      key_file: /home/ops/.ssh/ops.id_rsa
      force: yes
      accept_hostkey: yes

- name: install hex
  shell: cd /home/ops/rp-server/ && mix local.hex --force

- name: install rebar
  shell: cd /home/ops/rp-server/ && mix local.rebar --force

- name: compile project
  shell: cd /home/ops/rp-server/ && MIX_ENV=prod mix do deps.get, deps.compile --force

- name: mix release
  shell: cd /home/ops/rp-server/ &&  MIX_ENV=prod mix release --verbose --env=prod

- name: db migration 
  shell: cd /home/ops/rp-server/ && MIX_ENV=prod mix ecto.migrate

# - name: seeds
#   shell: cd /home/ops/rp-server/ && MIX_ENV=prod mix ecto.seed

- name: start rp_server daemon
  shell: HOSTNAME=127.0.0.1 REPLACE_OS_VARS=true sh /home/ops/rp-server/_build/prod/rel/rp_server/bin start

- name: change permission on rp_server folder
  file:
    path: /home/ops/rp-server
    owner: ops
  
    group: ops
    mode: 0755
    recurse: yes 

